/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutContactRouteImport } from './routes/_layout/contact'
import { Route as LayoutUsersRouteRouteImport } from './routes/_layout/users/route'
import { Route as LayoutUsersIndexRouteImport } from './routes/_layout/users/index'
import { Route as LayoutUsersIdRouteImport } from './routes/_layout/users/$id'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutContactRoute = LayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutUsersRouteRoute = LayoutUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutUsersIndexRoute = LayoutUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutUsersRouteRoute,
} as any)
const LayoutUsersIdRoute = LayoutUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LayoutUsersRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/users': typeof LayoutUsersRouteRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/contact': typeof LayoutContactRoute
  '/users/$id': typeof LayoutUsersIdRoute
  '/users/': typeof LayoutUsersIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof LayoutAboutRoute
  '/contact': typeof LayoutContactRoute
  '/': typeof LayoutIndexRoute
  '/users/$id': typeof LayoutUsersIdRoute
  '/users': typeof LayoutUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/users': typeof LayoutUsersRouteRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/users/$id': typeof LayoutUsersIdRoute
  '/_layout/users/': typeof LayoutUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/users' | '/about' | '/contact' | '/users/$id' | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/contact' | '/' | '/users/$id' | '/users'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/users'
    | '/_layout/about'
    | '/_layout/contact'
    | '/_layout/'
    | '/_layout/users/$id'
    | '/_layout/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/users/': {
      id: '/_layout/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof LayoutUsersIndexRouteImport
      parentRoute: typeof LayoutUsersRouteRoute
    }
    '/_layout/users/$id': {
      id: '/_layout/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof LayoutUsersIdRouteImport
      parentRoute: typeof LayoutUsersRouteRoute
    }
  }
}

interface LayoutUsersRouteRouteChildren {
  LayoutUsersIdRoute: typeof LayoutUsersIdRoute
  LayoutUsersIndexRoute: typeof LayoutUsersIndexRoute
}

const LayoutUsersRouteRouteChildren: LayoutUsersRouteRouteChildren = {
  LayoutUsersIdRoute: LayoutUsersIdRoute,
  LayoutUsersIndexRoute: LayoutUsersIndexRoute,
}

const LayoutUsersRouteRouteWithChildren =
  LayoutUsersRouteRoute._addFileChildren(LayoutUsersRouteRouteChildren)

interface LayoutRouteRouteChildren {
  LayoutUsersRouteRoute: typeof LayoutUsersRouteRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutUsersRouteRoute: LayoutUsersRouteRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutContactRoute: LayoutContactRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
